# Generated by Django 3.2.3 on 2021-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=200, verbose_name='sous-titre')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'a propos',
                'verbose_name_plural': 'a propos',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subtitle', models.CharField(max_length=200, verbose_name='sous-titre')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('message', models.TextField()),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='GlobalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img', verbose_name='bannière des autres pages du site')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bannière générale',
                'verbose_name_plural': 'Bannière générale',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='img')),
                ('link', models.CharField(max_length=200, verbose_name='lien-fa')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'réseau social',
                'verbose_name_plural': 'réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='adresse')),
                ('phone', models.CharField(max_length=200, verbose_name='téléphone')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('copyrights', models.CharField(max_length=200, verbose_name='copyright')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Information générale',
                'verbose_name_plural': 'Informations générales',
            },
        ),
    ]
