# Generated by Django 3.2.3 on 2021-05-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_socialnetwork_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
