# Generated by Django 3.2.3 on 2021-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_contact_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
