# Generated by Django 3.2.3 on 2021-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_website_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website',
            field=models.URLField(null=True, verbose_name='site web'),
        ),
    ]
