# Generated by Django 3.2.3 on 2021-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
