# Generated by Django 3.2.3 on 2021-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210520_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='nom'),
        ),
    ]
