# Generated by Django 3.2.3 on 2021-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210520_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_add',
            field=models.DateTimeField(verbose_name="date d'ajout"),
        ),
    ]
