# Generated by Django 3.2.3 on 2021-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout"),
        ),
    ]
