# Generated by Django 3.2.3 on 2021-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=50, null=True, verbose_name='icône'),
        ),
    ]
