# Generated by Django 3.2.3 on 2021-05-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
