# Generated by Django 3.2.3 on 2021-05-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_testimonial_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
