# Generated by Django 3.2.3 on 2021-05-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20210519_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
